#!/usr/bin/env php
<?php

require_once __DIR__ . '/components/autoload/autoload.php';

use components\console\Kernel;

$db_infos = json_decode(file_get_contents('config/db.json'), true);

new Kernel($argv, $db_infos);
