#!/usr/bin/env php
<?php

require_once __DIR__ . '/components/autoload/autoload.php';

use components\console\ConsoleKernel as Kernel;
use components\Yaml\Yaml;

$db_infos = Yaml::parse(file_get_contents('config/db.yml'));

new Kernel($argv, $db_infos);
